import type { Metadata } from "next";
import { Amiri, Inter_Tight } from "next/font/google";
import "./globals.css";
import Styles from "./layout.module.css";
import Nav from "@/components/Nav/Nav";

const interTight = Inter_Tight({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Sfwn",
  description: "Generated by sfwn",
};

// const amiri = Amiri({
//   subsets: ["arabic"],
//   display: "swap",
//   weight: "400",
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interTight.className} ${Styles.layout}`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
