import type { Metadata } from "next";
import { Aref_Ruqaa, Inter_Tight, Noto_Kufi_Arabic } from "next/font/google";
import "../globals.css";
import Styles from "./layout.module.css";
import { DictionaryProvider } from "@/context/DictionaryProvider";
import { getDictionary } from "./dictionaries";


const interTight = Inter_Tight({
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
  variable: "--inter-tight-font-family",
});

const notoKufi = Noto_Kufi_Arabic({
  subsets: ["arabic"],
  display: "swap",
  weight: ["400", "700"],
  variable: "--noto-kufi-font-family",
  preload: false,
})
const arefRuqaa = Aref_Ruqaa({
  subsets: ["arabic"],
  display: "swap",
  weight: ["400", "700"],
  variable: "--aref-ruqaa-font-family",
  preload: false,
})

export const metadata: Metadata = {
  title: "Sfwn",
  description: "Generated by sfwn",
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_VERIFICATION_TOKEN
  }
};

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'ar' }]
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>
}>) {
  const { lang } = await params
  const validLang = lang === "en" || lang === "ar" ? lang : "en"
  const dict = await getDictionary(validLang)

  return (
    <html lang={validLang} dir={validLang === "en" ? "ltr" : "rtl"}>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{if(localStorage.getItem('theme')==='light'){document.documentElement.classList.add('light');}}catch(e){}})();`,
          }}
        />
      </head>
      <body className={`
        ${validLang === "en" ? interTight.className : notoKufi.className}
        ${interTight.variable} ${notoKufi.variable} ${arefRuqaa.variable}
         ${Styles.layout}
         `}>
        <DictionaryProvider dictionary={dict}>
          {children}
        </DictionaryProvider>
      </body>
    </html>
  );
}
